[package]
name        = "std.encode"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Kodierung: Base64, URL-Encoding, UUID, Konvertierung, Pack"

[sources]
files = ["base64.lyx", "url.lyx", "uuid.lyx", "conv.lyx", "pack.lyx", "buffer.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.string = "^0.1.0"
