[package]
name        = "std.env"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Prozess-Umgebung: Argv, Environ"

[sources]
files = ["env.lyx"]

[dependencies]
std.alloc = "^0.1.0"
std.string = "^0.1.0"
