[package]
name        = "std.pdf"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "PDF-Erzeugung und -Analyse: Builder, Fonts, Grafik, Formulare, Verschlüsselung u.v.m."

[sources]
files = ["pdf.lyx", "pdf/builder.lyx", "pdf/objects.lyx", "pdf/page.lyx", "pdf/fonts.lyx", "pdf/graphics.lyx", "pdf/image.lyx", "pdf/compress.lyx", "pdf/meta.lyx", "pdf/outline.lyx", "pdf/annot.lyx", "pdf/attach.lyx", "pdf/forms.lyx", "pdf/layer.lyx", "pdf/namedest.lyx", "pdf/pagelabels.lyx", "pdf/pdfa.lyx", "pdf/reader.lyx", "pdf/shading.lyx", "pdf/spot.lyx", "pdf/transition.lyx", "pdf/ttfont.lyx", "pdf/viewprefs.lyx", "pdf/xmp.lyx", "pdf/xobject.lyx"]

[dependencies]
std.alloc    = "^0.1.0"
std.io       = "^0.1.0"
std.string   = "^0.1.0"
std.compress = "^0.1.0"
std.hash     = "^0.1.0"
std.encode   = "^0.1.0"
