[package]
name        = "std.ui"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "UI-Frameworks: LyxVision (TUI), Qt5-Bindings, X11"

[sources]
files = ["lyxvision/main.lyx", "lyxvision/app.lyx", "lyxvision/tapplication.lyx", "lyxvision/window.lyx", "lyxvision/frame.lyx", "lyxvision/view.lyx", "lyxvision/button.lyx", "lyxvision/inputline.lyx", "lyxvision/listview.lyx", "lyxvision/menu.lyx", "lyxvision/dialog.lyx", "lyxvision/statictext.lyx", "lyxvision/staticline.lyx", "lyxvision/cluster.lyx", "lyxvision/group.lyx", "lyxvision/terminal.lyx", "lyxvision/textdevice.lyx", "lyxvision/drivers.lyx", "lyxvision/consts.lyx", "lyxvision/types.lyx", "qt5_app.lyx", "qt5_core.lyx", "qt5_egl.lyx", "qt5_gl.lyx", "qt5_glx.lyx", "x11.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
