[package]
name        = "std.validate"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Validierung: IBAN, ISIN, ISBN, EAN, VAT, VIN, LEI, BIC u.v.m."

[sources]
files = ["validate/iban.lyx", "validate/isin.lyx", "validate/isbn.lyx", "validate/ean.lyx", "validate/vat.lyx", "validate/vin.lyx", "validate/lei.lyx", "validate/bic.lyx", "validate/luhn.lyx", "validate/issn.lyx", "validate/ismn.lyx", "validate/isrc.lyx", "validate/iso6346.lyx", "validate/iata.lyx", "validate/mmsi.lyx", "validate/orcid.lyx", "validate/uic.lyx", "validate/ewc.lyx", "validate/cas.lyx", "validate/de_numbers.lyx", "validate/de_personal.lyx", "validate/nl_bsn.lyx", "validate/ch_ahv.lyx", "validate/us_ssn.lyx", "validate/us_cusip.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.string = "^0.1.0"
