  chore/gitattributes[m
* [32mdocs/readme-network-update[m
  docs/virtual-abstract[m
  feat/abstract-functions[m
  feat/arm64-vmt-support[m
  feat/arrays[m
  feat/bgp-client[m
  feat/bitwise-operators[m
  feat/c-ffi[m
  feat/closures[m
  feat/dynlink-debug[m
  feat/dynlink-v2[m
  feat/frontend-literals[m
  feat/https-client[m
  feat/imap-client[m
  feat/ir-logic-ops[m
  feat/ldap-client[m
  feat/literals[m
  feat/lyxvision-framework[m
  feat/lyxvision-tview[m
  feat/lyxvision-v2[m
  feat/macos-arm64-vmt[m
  feat/mqtt-client[m
  feat/nested-functions[m
  feat/network[m
  feat/ntp-client[m
  feat/quic-client[m
  feat/readme-backends-update[m
  feat/sip-client[m
  feat/smtp-client[m
  feat/snmp-client[m
  feat/ssh-client[m
  feat/std-units[m
  feat/string-concat-format[m
  feat/target-arch-parameters[m
  feat/telnet-client[m
  feat/tobject-is-as-operator[m
  feat/units/fix-import-lowering-pub-filter[m
  feat/vmt-crossplatform[m
  feat/windows-x86-64-vmt[m
  feature/arrays[m
  feature/lyxvision-dirty-system[m
  feature/lyxvision-layout-engine[m
  feature/map-set-backends[m
  feature/window-arm64-emitter[m
  features/create-tests[m
  features/in-situ-data-visualizer[m
  features/ir-optimizer[m
  features/vmt[m
  fix/docs-update[m
  fix/dynamic-linking-debug[m
  fix/files[m
  fix/tech-debts[m
  func-jetbrains-aurum-plugin[m
  main[m
  refactor/lyxvision-subfolder[m
  string-conversion-integrate[m
  test/windows-vmt[m
  update/docu[m
+ [36mworktree-agent-a688132d[m
