[package]
name        = "std.fs"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Dateisystem: fs, fs_ext, xattr, inotify, mmap"

[sources]
files = ["fs.lyx", "fs_ext.lyx", "xattr.lyx", "inotify.lyx", "mmap_ext.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
