[package]
name        = "std.android"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Android NDK-Bindings: Activity, JNI, GLES2, Sensoren, Audio, APK-Builder u.v.m."

[sources]
files = ["android/native_activity.lyx", "android/app_glue.lyx", "android/jni.lyx", "android/gles2.lyx", "android/input.lyx", "android/sensor.lyx", "android/log.lyx", "android/looper.lyx", "android/asset.lyx", "android/native_window.lyx", "android/random.lyx", "android/ioctl.lyx", "android/zip_writer.lyx", "android/manifest_gen.lyx", "android/apk_builder.lyx", "android/restrictions.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
