[package]
name        = "std.formats"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Datenformate: JSON, XML, HTML, YAML, INI"

[sources]
files = ["json.lyx", "xml.lyx", "html.lyx", "yaml.lyx", "ini.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
