[package]
name        = "std.cloud.gcp"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "GCP SDK: Cloud Storage, Compute Engine, Firestore, Pub/Sub, Cloud Functions, Cloud Run, Cloud Logging, Cloud Monitoring, Secret Manager, IAM"

[sources]
files = [
    "crypto/rsa.lyx",
    "cloud/gcp/jwt.lyx",
    "cloud/gcp/oauth.lyx",
    "cloud/gcp/credentials.lyx",
    "cloud/gcp/transport.lyx",
    "cloud/gcp/storage.lyx",
    "cloud/gcp/compute.lyx",
    "cloud/gcp/firestore.lyx",
    "cloud/gcp/pubsub.lyx",
    "cloud/gcp/functions.lyx",
    "cloud/gcp/logging.lyx",
    "cloud/gcp/secrets.lyx"
]

[dependencies]
std.alloc   = "^0.1.0"
std.string  = "^0.1.0"
std.net     = "^0.1.0"
std.crypto  = "^0.1.0"
std.encode  = "^0.1.0"
std.time    = "^0.1.0"
std.fs      = "^0.1.0"
std.os      = "^0.1.0"
