[package]
name        = "std.db"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Datenbanken: SQLite, PostgreSQL, MySQL, Redis"

[sources]
files = ["db/sqlite.lyx", "db/postgres.lyx", "db/mysql.lyx", "db/redis.lyx", "db/redis_simple.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
std.net    = "^0.1.0"
