[package]
name        = "std.collections"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Datenstrukturen: Sort, List, Buffer"

[sources]
files = ["sort.lyx", "list.lyx", "buffer.lyx"]

[dependencies]
std.alloc = "^0.1.0"
