{$mode objfpc}{$H+}
unit asm_listing;

{
  Assembly Listing Generator (aerospace-todo 6.1)
  
  Generiert ein lesbares Assembly-Listing mit Source-Zeilennummern
  für Audit, Debugging und DO-178C Zertifizierung.
  
  Format:
    ; source_file:line
    00000000  48 89 E5          push rbp
    00000003  48 83 EC 10       sub rsp, 16
    ; main.lyx:5
    00000007  48 C7 C0 0A 00 00 00  mov rax, 10
}

interface

uses
  SysUtils, Classes, ir, bytes, TypInfo;

type
  TAsmListingGenerator = class
  private
    FModule: TIRModule;
    FCodeBuf: TByteBuffer;
    FDataBuf: TByteBuffer;
    FOutput: TStringList;
    FArch: string;
    
    procedure EmitHeader;
    procedure EmitFunctionListing(fn: TIRFunction; codeStart: Integer);
    procedure EmitDataSection;
    function DisassembleByte(offset: Integer; out mnemonic: string; out size: Integer): string;
    function DisassembleX86_64(offset: Integer; out mnemonic: string; out size: Integer): string;
    function DisassembleARM64(offset: Integer; out mnemonic: string; out size: Integer): string;
    function DisassembleRISCV(offset: Integer; out mnemonic: string; out size: Integer): string;
    function DisassembleXtensa(offset: Integer; out mnemonic: string; out size: Integer): string;
    
  public
    constructor Create(module: TIRModule; codeBuf, dataBuf: TByteBuffer; const arch: string);
    destructor Destroy; override;
    
    function Generate: string;
  end;

implementation

constructor TAsmListingGenerator.Create(module: TIRModule; codeBuf, dataBuf: TByteBuffer; const arch: string);
begin
  inherited Create;
  FModule := module;
  FCodeBuf := codeBuf;
  FDataBuf := dataBuf;
  FArch := LowerCase(arch);
  FOutput := TStringList.Create;
end;

destructor TAsmListingGenerator.Destroy;
begin
  FOutput.Free;
  inherited Destroy;
end;

function TAsmListingGenerator.Generate: string;
var
  i: Integer;
  fn: TIRFunction;
  codeStart: Integer;
begin
  FOutput.Clear;
  
  EmitHeader;
  
  codeStart := 0;
  for i := 0 to High(FModule.Functions) do
  begin
    fn := FModule.Functions[i];
    // Find code offset for this function
    if i > 0 then
    begin
      // Approximate: each function's code starts after the previous one
      // This is a simplification; the backend tracks exact offsets
    end;
    EmitFunctionListing(fn, codeStart);
    codeStart := codeStart + Length(fn.Instructions) * 4;  // rough estimate
  end;
  
  EmitDataSection;
  
  Result := FOutput.Text;
end;

procedure TAsmListingGenerator.EmitHeader;
begin
  FOutput.Add('; ================================================');
  FOutput.Add('; Lyx Assembly Listing');
  FOutput.Add('; Generated by lyxc v0.7.0-aerospace');
  FOutput.Add('; DO-178C TQL-5 Qualified Compiler');
  FOutput.Add('; Architecture: ' + FArch);
  FOutput.Add('; ================================================');
  FOutput.Add('');
end;

procedure TAsmListingGenerator.EmitFunctionListing(fn: TIRFunction; codeStart: Integer);
var
  i: Integer;
  instr: TIRInstr;
  offset: Integer;
  hexBytes: string;
  mnemonic: string;
  size: Integer;
  srcLine: string;
  j: Integer;
  b: Byte;
begin
  FOutput.Add('; -----------------------------------------------');
  FOutput.Add('; Function: ' + fn.Name);
  FOutput.Add('; Locals: ' + IntToStr(fn.LocalCount) + ', Instructions: ' + IntToStr(Length(fn.Instructions)));
  FOutput.Add('; -----------------------------------------------');
  FOutput.Add('');
  
  offset := codeStart;
  for i := 0 to High(fn.Instructions) do
  begin
    instr := fn.Instructions[i];
    
    // Source line comment
    if (instr.SourceLine > 0) and (instr.SourceFile <> '') then
    begin
      srcLine := ExtractFileName(instr.SourceFile) + ':' + IntToStr(instr.SourceLine);
      FOutput.Add('  ; ' + srcLine);
    end;
    
    // IR instruction comment
    case instr.Op of
      irConstInt:   mnemonic := 'const_int t' + IntToStr(instr.Dest) + ', ' + IntToStr(instr.ImmInt);
      irConstStr:   mnemonic := 'const_str t' + IntToStr(instr.Dest) + ', "' + instr.ImmStr + '"';
      irAdd:        mnemonic := 'add t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irSub:        mnemonic := 'sub t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irMul:        mnemonic := 'mul t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irDiv:        mnemonic := 'div t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irMod:        mnemonic := 'mod t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irNeg:        mnemonic := 'neg t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1);
      irNot:        mnemonic := 'not t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1);
      irAnd:        mnemonic := 'and t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irOr:         mnemonic := 'or  t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irXor:        mnemonic := 'xor t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irNor:        mnemonic := 'nor t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irShl:        mnemonic := 'shl t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irShr:        mnemonic := 'shr t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irCmpEq:      mnemonic := 'cmp_eq t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irCmpNeq:     mnemonic := 'cmp_ne t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irCmpLt:      mnemonic := 'cmp_lt t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irCmpLe:      mnemonic := 'cmp_le t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irCmpGt:      mnemonic := 'cmp_gt t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irCmpGe:      mnemonic := 'cmp_ge t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + ', t' + IntToStr(instr.Src2);
      irLoadLocal:  mnemonic := 'load t' + IntToStr(instr.Dest) + ', [local' + IntToStr(instr.Src1) + ']';
      irStoreLocal: mnemonic := 'store [local' + IntToStr(instr.Dest) + '], t' + IntToStr(instr.Src1);
      irJmp:        mnemonic := 'jmp ' + instr.LabelName;
      irBrTrue:     mnemonic := 'br_true t' + IntToStr(instr.Src1) + ', ' + instr.LabelName;
      irBrFalse:    mnemonic := 'br_false t' + IntToStr(instr.Src1) + ', ' + instr.LabelName;
      irLabel:      mnemonic := instr.LabelName + ':';
      irFuncExit:   if instr.Src1 >= 0 then mnemonic := 'ret t' + IntToStr(instr.Src1) else mnemonic := 'ret';
      irCall:       mnemonic := 'call ' + instr.ImmStr;
      irCallBuiltin:mnemonic := 'builtin ' + instr.ImmStr;
      irPanic:      mnemonic := 'panic t' + IntToStr(instr.Src1);
      irCast:       mnemonic := 'cast t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1);
      irLoadElem:   mnemonic := 'load_elem t' + IntToStr(instr.Dest) + ', t' + IntToStr(instr.Src1) + '[t' + IntToStr(instr.Src2) + ']';
      irStoreElem:  mnemonic := 'store_elem t' + IntToStr(instr.Src1) + '[t' + IntToStr(instr.Src2) + '], t' + IntToStr(instr.Src3);
      irAlloc:      mnemonic := 'alloc t' + IntToStr(instr.Dest) + ', ' + IntToStr(instr.ImmInt) + ' bytes';
      irFree:       mnemonic := 'free t' + IntToStr(instr.Src1);
    else
      mnemonic := 'ir_' + GetEnumName(TypeInfo(TIROpKind), Ord(instr.Op)) +
                  ' d=' + IntToStr(instr.Dest) +
                  ' s1=' + IntToStr(instr.Src1) +
                  ' s2=' + IntToStr(instr.Src2);
    end;
    
    // Hex bytes (up to 8 bytes per instruction)
    hexBytes := '';
    size := 0;
    for j := 0 to 7 do
    begin
      if (offset + j < FCodeBuf.Size) then
      begin
        b := FCodeBuf.ReadU8(offset + j);
        hexBytes := hexBytes + IntToHex(b, 2) + ' ';
        Inc(size);
      end
      else
        hexBytes := hexBytes + '   ';
    end;
    
    // Format: offset  hex bytes              mnemonic
    FOutput.Add(Format('  %08X  %-24s %s', [offset, Trim(hexBytes), mnemonic]));
    
    Inc(offset, size);
  end;
  FOutput.Add('');
end;

procedure TAsmListingGenerator.EmitDataSection;
var
  i: Integer;
  hexLine: string;
  j: Integer;
  b: Byte;
begin
  if (FDataBuf = nil) or (FDataBuf.Size = 0) then
    Exit;
    
  FOutput.Add('; ================================================');
  FOutput.Add('; Data Section');
  FOutput.Add('; ================================================');
  FOutput.Add('');
  
  // Strings
  if Assigned(FModule) and (FModule.Strings.Count > 0) then
  begin
    FOutput.Add('; Strings');
    for i := 0 to FModule.Strings.Count - 1 do
    begin
      FOutput.Add(Format('  .str%d: db "%s", 0', [i, FModule.Strings[i]]));
    end;
    FOutput.Add('');
  end;
  
  // Raw data bytes
  FOutput.Add('; Raw data bytes');
  i := 0;
  while i < FDataBuf.Size do
  begin
    hexLine := Format('  %08X  ', [i]);
    for j := 0 to 15 do
    begin
      if (i + j < FDataBuf.Size) then
      begin
        b := FDataBuf.ReadU8(i + j);
        hexLine := hexLine + IntToHex(b, 2) + ' ';
      end
      else
        hexLine := hexLine + '   ';
    end;
    FOutput.Add(hexLine);
    Inc(i, 16);
  end;
  FOutput.Add('');
end;

function TAsmListingGenerator.DisassembleByte(offset: Integer; out mnemonic: string; out size: Integer): string;
begin
  Result := '';
  mnemonic := '';
  size := 0;
end;

function TAsmListingGenerator.DisassembleX86_64(offset: Integer; out mnemonic: string; out size: Integer): string;
begin
  Result := '';
  mnemonic := '';
  size := 0;
end;

function TAsmListingGenerator.DisassembleARM64(offset: Integer; out mnemonic: string; out size: Integer): string;
begin
  Result := '';
  mnemonic := '';
  size := 0;
end;

function TAsmListingGenerator.DisassembleRISCV(offset: Integer; out mnemonic: string; out size: Integer): string;
begin
  Result := '';
  mnemonic := '';
  size := 0;
end;

function TAsmListingGenerator.DisassembleXtensa(offset: Integer; out mnemonic: string; out size: Integer): string;
begin
  Result := '';
  mnemonic := '';
  size := 0;
end;

end.
