[package]
name        = "std.hash"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Hashing: SHA-256, HMAC, MD5, bcrypt, Argon2"

[sources]
files = ["hash.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.string = "^0.1.0"
