[package]
name        = "std.cloud.do"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "DigitalOcean SDK: Droplets, Kubernetes, Datenbanken, Spaces, Functions u.v.m."

[sources]
files = ["cloud/do/core.lyx", "cloud/do/credentials.lyx", "cloud/do/transport.lyx", "cloud/do/droplets.lyx", "cloud/do/kubernetes.lyx", "cloud/do/databases.lyx", "cloud/do/spaces.lyx", "cloud/do/volumes.lyx", "cloud/do/networking.lyx", "cloud/do/monitoring.lyx", "cloud/do/functions.lyx", "cloud/do/apps.lyx", "cloud/do/registry.lyx"]

[dependencies]
std.alloc   = "^0.1.0"
std.string  = "^0.1.0"
std.net     = "^0.1.0"
std.formats = "^0.1.0"
