[package]
name        = "std.cloud.aws"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "AWS SDK: S3, EC2, Lambda, DynamoDB, SQS, SNS, IAM, Secrets, CloudWatch"

[sources]
files = ["cloud/aws/core.lyx", "cloud/aws/sigv4.lyx", "cloud/aws/transport.lyx", "cloud/aws/xml.lyx", "cloud/s3.lyx", "cloud/ec2.lyx", "cloud/lambda.lyx", "cloud/dynamodb.lyx", "cloud/sqs.lyx", "cloud/sns.lyx", "cloud/iam.lyx", "cloud/secrets.lyx", "cloud/cloudwatch.lyx"]

[dependencies]
std.alloc   = "^0.1.0"
std.string  = "^0.1.0"
std.net     = "^0.1.0"
std.hash    = "^0.1.0"
std.crypto  = "^0.1.0"
std.formats = "^0.1.0"
