[package]
name        = "std.hardware"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Hardware-Treiber: GPIO, USB, Bluetooth, Raspberry Pi 4"

[sources]
files = ["hardware/gpio_pin.lyx", "hardware/gpio_mmio.lyx", "hardware/gpio_ioctl.lyx", "hardware/gpio_syscalls.lyx", "hardware/gpio_ext.lyx", "hardware/gpio_barriers.lyx", "hardware/gpio_util.lyx", "hardware/usb_types.lyx", "hardware/usb_syscalls.lyx", "hardware/usb_discovery.lyx", "hardware/usb_control.lyx", "hardware/usb_bulk.lyx", "hardware/usb_interrupt.lyx", "hardware/usb_iso.lyx", "hardware/usb_parse.lyx", "hardware/usb_urb_pool.lyx", "hardware/usb_endpoint_types.lyx", "hardware/usb_endpoint_bind.lyx", "hardware/usb_ifc_mgr.lyx", "hardware/usb_util.lyx", "hardware/bluetooth.lyx", "hardware/bluetooth_types.lyx", "hardware/bluetooth_dbus.lyx", "hardware/bluetooth_gattc.lyx", "hardware/bluetooth_gatts.lyx", "hardware/bluetooth_l2cap.lyx", "hardware/bluetooth_rfcomm.lyx", "hardware/bluetooth_ext.lyx", "hardware/bluetooth_ai.lyx", "hardware/rpi4.lyx"]

[dependencies]
std.alloc = "^0.1.0"
std.io    = "^0.1.0"
