[package]
name        = "std.tar"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "TAR-Archiv Lesen und Schreiben (POSIX ustar, keine Komprimierung)"

[sources]
files = ["tar.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
std.fs     = "^0.1.0"
