[package]
name        = "std.blockchain"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Blockchain-Bibliothek: SHA-256, ECDSA, Serializer, Core-Models, Ledger, Consensus (WP-BL-02..05)"

[sources]
files = ["blockchain.lyx"]

[dependencies]
std.alloc       = "^0.1.0"
std.crypto.sha256 = "^0.1.0"
std.crypto.ecc  = "^0.1.0"
std.crypto.rand = "^0.1.0"
std.time        = "^0.1.0"
