[package]
name        = "std.zstd"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Zstd-Kompressor (Store-Modus) und -Dekompressor (RFC 8878)"

[sources]
files = ["zstd.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
