[package]
name        = "std.system"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Systeminfo, Sysadmin, Scheduling, Threads"

[sources]
files = ["system.lyx", "systeminfo.lyx", "sysadmin.lyx", "sched.lyx", "thread.lyx", "meta_safe.lyx", "security_ext.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
