[package]
name        = "std.cloud.cf"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Cloudflare SDK: Workers, KV, R2, D1, DNS, WAF, Pages, Tunnel u.v.m."

[sources]
files = ["cloud/cf/core.lyx", "cloud/cf/credentials.lyx", "cloud/cf/transport.lyx", "cloud/cf/workers.lyx", "cloud/cf/kv.lyx", "cloud/cf/r2.lyx", "cloud/cf/d1.lyx", "cloud/cf/dns.lyx", "cloud/cf/waf.lyx", "cloud/cf/pages.lyx", "cloud/cf/tunnel.lyx", "cloud/cf/lb.lyx", "cloud/cf/zones.lyx", "cloud/cf/cache.lyx", "cloud/cf/analytics.lyx", "cloud/cf/email.lyx"]

[dependencies]
std.alloc   = "^0.1.0"
std.string  = "^0.1.0"
std.net     = "^0.1.0"
std.formats = "^0.1.0"
