[package]
name        = "std.net"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Netzwerk: Sockets, HTTP/S, TLS, DNS, SMTP, IMAP, SSH, MQTT, QUIC u.v.m."

[sources]
files = ["net/socket.lyx", "net/types.lyx", "net/syscalls.lyx", "net/epoll.lyx", "net/internal/types.lyx", "net/internal/syscalls_linux.lyx", "net/internal/syscalls_android.lyx", "net/http.lyx", "net/https.lyx", "net/tls.lyx", "net/asn1.lyx", "net/dns.lyx", "net/smtp.lyx", "net/imap.lyx", "net/ssh.lyx", "net/mqtt.lyx", "net/ntp.lyx", "net/telnet.lyx", "net/sip.lyx", "net/snmp.lyx", "net/whois.lyx", "net/bgp.lyx", "net/ldap.lyx", "net/quic.lyx", "net/mongo.lyx"]

[dependencies]
std.alloc   = "^0.1.0"
std.io      = "^0.1.0"
std.string  = "^0.1.0"
std.hash    = "^0.1.0"
std.crypto  = "^0.1.0"
std.formats = "^0.1.0"
