[package]
name        = "std.io"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "I/O-Primitives: Print, PrintLn, ReadFile, WriteFile, Stdin"

[sources]
files = ["io.lyx"]

[dependencies]
std.alloc = "^0.1.0"
