[package]
name        = "std.ipc"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Inter-Process-Communication: Pipes, Signals, SysV-IPC, MQueue, io_uring, BPF"

[sources]
files = ["pipe.lyx", "signals.lyx", "ipc_sysv.lyx", "mqueue.lyx", "io_uring.lyx", "bpf.lyx"]

[dependencies]
std.alloc = "^0.1.0"
std.io    = "^0.1.0"
