[package]
name        = "std.iso"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "ISO 9660 Lesen und Schreiben (Level 1, keine Komprimierung, Flat Root für Writer)"

[sources]
files = ["iso.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
std.fs     = "^0.1.0"
