[package]
name        = "std.error"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Fehlerbehandlung: error, result, debug"

[sources]
files = ["error.lyx", "result.lyx", "debug.lyx"]

[dependencies]
std.alloc = "^0.1.0"
std.io     = "^0.1.0"
