[package]
name        = "std.process"
version     = "0.1.0"
author      = "Andreas Röne"
license     = "MIT"
description = "Prozesse & Laufzeit: process, os, ns, crt"

[sources]
files = ["process.lyx", "process_ext.lyx", "os.lyx", "ns.lyx", "crt.lyx", "crt_raw.lyx"]

[dependencies]
std.alloc  = "^0.1.0"
std.io     = "^0.1.0"
std.string = "^0.1.0"
std.fs     = "^0.1.0"
